#pragma once

enum MapNumber
{
	PIZZA_BAKERY_MAP_0,
	VEGETABLE_BEVERAGE_STORE_MAP_1,
	FLOUR_STORE_HOSPITAL_MAP_2,
	NUMBER_OF_VILLAGE_MAP
};

enum BuildingNumber
{
	PIZZA_BAKERY_0,
	VEGETABLE_STORE_1,
	BEVERAGE_STORE_2,
	FLOUR_STORE_3,
	HOSPITAL_4,
	NUMBER_OF_BIULDING
};